default_agent: marketplaceAgent
agents:
  marketplaceAgent:
    name: marketplaceAgent
    entrypoint: agentcore_app.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::605345174368:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-29855fdc98
      execution_role_auto_create: false
      account: '605345174368'
      region: us-east-1
      ecr_repository: 605345174368.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-marketplaceagent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: marketplaceAgent-MmeCs3B9mE
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:605345174368:runtime/marketplaceAgent-MmeCs3B9mE
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-marketplaceagent-builder
      execution_role: arn:aws:iam::605345174368:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-29855fdc98
      source_bucket: bedrock-agentcore-codebuild-sources-605345174368-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: marketplaceAgent_mem-gMEb015LD3
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:605345174368:memory/marketplaceAgent_mem-gMEb015LD3
      memory_name: marketplaceAgent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
